"""Phase 2 transform: staging CSVs -> fact + dimension set.

Python port of the workbook's Power Query layer (VTU Report - Sales
Analysis documentation, section 3). Reads the five staging CSVs written by
``pull_report_data.py`` plus the manually maintained
``product_template_name.xlsx``, and produces the final fact table
(``report_invoiced.csv``, section 3.11) and the dimension tables the Power
Pivot model consumes (section 4.1).

Differences vs. the legacy Power Query logic, all documented in the
roadmap:

- The legacy cleaning of literal ``"False"`` text (spec sections 3.6 step 1
  and 3.8 step 3) is skipped: the phase-1 extract already writes empty
  strings.
- The company mapping includes PRM B.V. (id 2), which the legacy
  replacement rules missed (section 5.4).
- The ``special_category`` product-id lists, the company mapping and the
  UoM factor table live in ``config/transform_rules.json`` instead of being
  hard-coded (section 5.5).
- The refresh timestamp is generated by the pipeline instead of read from
  SharePoint file metadata (section 3.1).
- Week numbering defaults to the legacy Power Query semantics
  (``Date.WeekOfYear`` with Monday start: week 1 contains January 1), so
  historical week buckets are preserved; true ISO 8601 numbering is
  available as an option (section 3.4).
"""

from __future__ import annotations

import csv
import datetime as dt
import json
import os
from dataclasses import dataclass, field
from typing import Any, Iterable

# English month abbreviations, locale-independent, for the sortable
# "04. Apr" MonthName style of the legacy dim_date (spec section 3.4).
MONTH_ABBR = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

FACT_COLUMNS = (
    "Name", "PartnerID", "partner_name", "CurrencyID", "CurrencyValue",
    "accounting_date", "company_id", "account_id", "debit", "credit",
    "balance", "product_id", "quantity", "price_subtotal",
    "quantity_product_uom", "price_subtotal_eur", "special_category",
    "Invoiced Amount",
)


class TransformError(Exception):
    """A problem with inputs or configuration the user must fix."""


# --- Rules (config/transform_rules.json) -------------------------------------


@dataclass(frozen=True)
class Rules:
    """Maintenance data: classification rules and static lookup tables."""

    rental_accounts: frozenset[str]
    special_product_ids: frozenset[int]
    rss_product_ids: frozenset[int]
    company_names: dict[int, str]
    uom_factors: dict[int, float]
    uom_names: dict[int, str]


def load_rules(path: str) -> Rules:
    try:
        with open(path, encoding="utf-8") as fh:
            raw = json.load(fh)
    except FileNotFoundError:
        raise TransformError(f"Rules file not found: {path}") from None
    except json.JSONDecodeError as exc:
        raise TransformError(f"Rules file {path} is not valid JSON: {exc}") from None

    try:
        special = raw["special_category"]
        return Rules(
            rental_accounts=frozenset(special["rental_accounts"]),
            special_product_ids=frozenset(int(i) for i in special["special_product_ids"]),
            rss_product_ids=frozenset(int(i) for i in special["rss_product_ids"]),
            company_names={int(c["id"]): c["name"] for c in raw["companies"]},
            uom_factors={int(u["uom_id"]): float(u["factor"]) for u in raw["uom_factors"]},
            uom_names={int(u["uom_id"]): u["name"] for u in raw["uom_factors"]},
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise TransformError(f"Rules file {path} is malformed: {exc}") from None


# --- Value parsing ------------------------------------------------------------


def parse_m2o(value: str) -> tuple[int | None, str]:
    """Split a staged many2one value ``[id,"Display Name"]`` into (id, name).

    The extract writes many2one fields as a JSON pair; empty fields are "".
    """
    if not value:
        return None, ""
    try:
        pair = json.loads(value)
    except json.JSONDecodeError:
        return None, value
    if isinstance(pair, list) and len(pair) == 2:
        return int(pair[0]), str(pair[1])
    return None, value


def to_float(value: str) -> float | None:
    return float(value) if value else None


def to_int(value: str) -> int | None:
    return int(float(value)) if value else None


# --- Input readers ------------------------------------------------------------


def read_staging_csv(input_dir: str, name: str) -> list[dict[str, str]]:
    path = os.path.join(input_dir, name)
    try:
        with open(path, newline="", encoding="utf-8") as fh:
            return list(csv.DictReader(fh))
    except FileNotFoundError:
        raise TransformError(
            f"Staging file not found: {path}. Run pull_report_data.py first "
            "(phase 1) so the staging CSVs exist."
        ) from None


def read_dutch_names(path: str) -> dict[int, str]:
    """Read the manual Dutch product-name mapping (spec section 2.6).

    Sheet1 with columns ``ID`` (product template id) and ``Naam``.
    """
    if not os.path.exists(path):
        raise TransformError(
            f"Manual product-name mapping not found: {path}. This file is "
            "maintained by hand and cannot be regenerated - restore it from "
            "your backup (expected columns: ID, Naam on Sheet1), or point "
            "--product-names at its location."
        )

    from openpyxl import load_workbook  # deferred: only needed here

    workbook = load_workbook(path, read_only=True, data_only=True)
    try:
        sheet = workbook["Sheet1"] if "Sheet1" in workbook.sheetnames else workbook.worksheets[0]
        rows = sheet.iter_rows(values_only=True)
        header = [str(cell).strip() if cell is not None else "" for cell in next(rows, [])]
        try:
            id_col, name_col = header.index("ID"), header.index("Naam")
        except ValueError:
            raise TransformError(
                f"{path}: sheet {sheet.title!r} must have 'ID' and 'Naam' "
                f"columns, found {header!r}."
            ) from None

        names: dict[int, str] = {}
        for row in rows:
            template_id = row[id_col] if id_col < len(row) else None
            name = row[name_col] if name_col < len(row) else None
            if template_id is None or name in (None, ""):
                continue
            names[int(template_id)] = str(name)
        return names
    finally:
        workbook.close()


# --- Fact table (spec sections 3.8-3.11) ---------------------------------------


@dataclass
class FactStats:
    """What the fact build kept and dropped, for the run summary."""

    headers_total: int = 0
    headers_kept: int = 0
    headers_not_posted: int = 0
    headers_before_cutoff: int = 0
    lines_total: int = 0
    lines_kept: int = 0
    unknown_company_ids: set[int] = field(default_factory=set)
    missing_uom_ids: dict[int, str] = field(default_factory=dict)


def special_category(account_name: str, product_id: int | None, rules: Rules) -> str:
    """Business classification of a line (spec section 3.9)."""
    if account_name in rules.rental_accounts:
        return "Rental Order"
    if product_id is None or product_id in rules.special_product_ids:
        return "Special Category"
    if product_id in rules.rss_product_ids:
        return "Normal - RSS"
    return "Normal"


def build_fact(
    headers: list[dict[str, str]],
    lines: list[dict[str, str]],
    rules: Rules,
    cutoff: dt.date,
) -> tuple[list[dict[str, Any]], FactStats]:
    """Filter headers, enrich lines, inner-join them into the final fact."""
    stats = FactStats(headers_total=len(headers), lines_total=len(lines))

    # Headers (3.8): posted only, on/after the cutoff, company label,
    # PartnerID split.
    kept_headers: dict[int, dict[str, Any]] = {}
    for header in headers:
        if header["State"] != "posted":
            stats.headers_not_posted += 1
            continue
        accounting_date = header["accounting_date"]
        if not accounting_date or dt.date.fromisoformat(accounting_date[:10]) < cutoff:
            stats.headers_before_cutoff += 1
            continue

        partner_id, partner_name = parse_m2o(header["PartnerID"])
        company_id, company_raw_name = parse_m2o(header["company_id"])
        company_label = rules.company_names.get(company_id)  # type: ignore[arg-type]
        if company_label is None:
            # No mapping rule: keep the raw display name (legacy kept the
            # raw pair) and surface it in the run summary.
            company_label = company_raw_name or header["company_id"]
            if company_id is not None:
                stats.unknown_company_ids.add(company_id)

        kept_headers[int(header["account_move_id"])] = {
            "Name": header["Name"],
            "PartnerID": partner_id,
            "partner_name": partner_name,
            "CurrencyID": to_int(header["CurrencyID"]),
            "CurrencyValue": header["CurrencyValue"],
            "accounting_date": accounting_date[:10],
            "company_id": company_label,
        }
    stats.headers_kept = len(kept_headers)

    # Lines (3.9) + inner join (3.10) + Invoiced Amount (3.11).
    fact: list[dict[str, Any]] = []
    for line in lines:
        move_id, _ = parse_m2o(line["account_move_id"])
        header_part = kept_headers.get(move_id)  # type: ignore[arg-type]
        if header_part is None:
            continue  # line of a non-posted or pre-cutoff invoice

        product_id, _ = parse_m2o(line["product_id"])
        uom_id, uom_name = parse_m2o(line["product_uom_id"])
        quantity = to_float(line["quantity"])

        factor = rules.uom_factors.get(uom_id) if uom_id is not None else None
        if uom_id is not None and factor is None:
            stats.missing_uom_ids.setdefault(uom_id, uom_name)
        if quantity is None or not factor:
            quantity_product_uom = quantity  # legacy null-factor behaviour
        else:
            quantity_product_uom = quantity / factor

        price_subtotal = to_float(line["price_subtotal"])
        currency_rate = to_float(line["currency_rate"])
        if price_subtotal is None or not currency_rate:
            price_subtotal_eur = price_subtotal
        else:
            price_subtotal_eur = price_subtotal / currency_rate

        balance = to_float(line["balance"])

        row = dict(header_part)
        row.update(
            {
                "account_id": line["account_id"],
                "debit": to_float(line["debit"]),
                "credit": to_float(line["credit"]),
                "balance": balance,
                "product_id": product_id,
                "quantity": quantity,
                "price_subtotal": price_subtotal,
                "quantity_product_uom": quantity_product_uom,
                "price_subtotal_eur": price_subtotal_eur,
                "special_category": special_category(line["account_id"], product_id, rules),
                "Invoiced Amount": -balance if balance is not None else None,
            }
        )
        fact.append(row)
    stats.lines_kept = len(fact)

    return fact, stats


# --- Dimensions (spec sections 3.2-3.7) ----------------------------------------


def build_dim_product(
    products: list[dict[str, str]], dutch_names: dict[int, str]
) -> list[dict[str, Any]]:
    """Enrich product_template.csv with references and Dutch names (3.6)."""
    rows = []
    for product in products:
        display_name = product["display_name"]
        if "[" in display_name and "]" in display_name:
            internal_reference = display_name.split("[", 1)[1].split("]", 1)[0]
        else:
            internal_reference = ""
        if "] " in display_name:
            name_english = display_name.split("] ", 1)[1]
        else:
            name_english = display_name

        name_dutch = dutch_names.get(int(product["id"]), "")
        preferred_name = name_dutch or name_english
        preferred_ref = product["prodin_reference"] or internal_reference
        prodin_ref_name = f"[{preferred_ref}] {preferred_name}" if preferred_ref else preferred_name
        display_name_dutch = (
            f"[{internal_reference}] {preferred_name}" if internal_reference else preferred_name
        )

        rows.append(
            {
                "id": to_int(product["id"]),
                "product_id": to_int(product["product_id"]),
                "display_name": display_name,
                "internal_reference": internal_reference,
                "prodin_reference": product["prodin_reference"],
                "product_name_english": name_english,
                "product_name_dutch": name_dutch,
                "prodin_ref_name": prodin_ref_name,
                "display_name_dutch": display_name_dutch,
                "list_price": to_float(product["list_price"]),
                "standard_price": to_float(product["standard_price"]),
                "report_category_name": product["report_category_name"] or "Z. Category N/A",
            }
        )
    return rows


def build_dim_partner(partners: list[dict[str, str]]) -> list[dict[str, Any]]:
    """res_partner.csv with the country name extracted (2.5)."""
    return [
        {
            "id": to_int(partner["id"]),
            "name": partner["name"],
            "commercial_company_name": partner["commercial_company_name"],
            "country_id": parse_m2o(partner["country_id"])[1],
        }
        for partner in partners
    ]


def build_dim_currency(currencies: list[dict[str, str]]) -> list[dict[str, Any]]:
    """res_currency.csv is already the dimension (2.4)."""
    return [
        {
            "id": to_int(currency["id"]),
            "currency": currency["currency"],
            "latest_rate": to_float(currency["latest_rate"]),
            "latest_rate_date": currency["latest_rate_date"],
            "symbol": currency["symbol"],
        }
        for currency in currencies
    ]


def legacy_week_number(day: dt.date) -> int:
    """Power Query ``Date.WeekOfYear(_, Day.Monday)``: week 1 is the week
    containing January 1, weeks start on Monday. Not ISO 8601 - kept for
    continuity of historical week buckets (spec section 3.4)."""
    jan1 = dt.date(day.year, 1, 1)
    week1_start = jan1 - dt.timedelta(days=jan1.weekday())
    return (day - week1_start).days // 7 + 1


def build_dim_date(start: dt.date, end: dt.date, iso_weeks: bool) -> list[dict[str, Any]]:
    """Daily calendar from start to end inclusive (spec section 3.4)."""
    rows = []
    for offset in range((end - start).days + 1):
        day = start + dt.timedelta(days=offset)
        if iso_weeks:
            iso = day.isocalendar()
            week, week_year = iso[1], iso[0]
        else:
            week, week_year = legacy_week_number(day), day.year
        week_2d = f"{week:02d}"
        year_2d = f"{week_year % 100:02d}"
        rows.append(
            {
                "Date": day.isoformat(),
                "Year": day.year,
                "MonthName": f"{day.month:02d}. {MONTH_ABBR[day.month - 1]}",
                "MonthNumber": day.month,
                "yyyy-qq": f"{day.year}-Q{(day.month - 1) // 3 + 1}",
                "WeekNumber": week,
                "Week_2d": week_2d,
                "Year_2d": year_2d,
                "YY-WW": f"{year_2d}-{week_2d}",
                "YearWeekKey": week_year * 100 + week,
            }
        )
    return rows


def build_dim_uom(rules: Rules) -> list[dict[str, Any]]:
    return [
        {"uom_id": uom_id, "name": rules.uom_names[uom_id], "factor": factor}
        for uom_id, factor in sorted(rules.uom_factors.items())
    ]


def build_dim_company(rules: Rules) -> list[dict[str, Any]]:
    return [
        {"company_id": company_id, "company_name": name}
        for company_id, name in sorted(rules.company_names.items())
    ]


def build_refresh_date_time(generated_at: dt.datetime) -> list[dict[str, Any]]:
    """Pipeline-generated replacement for the SharePoint file timestamp (3.1)."""
    return [
        {
            "refresh_file_datetime": generated_at.strftime("%Y-%m-%d %H:%M:%S"),
            "join_id1": 1,
        }
    ]


# --- Output -------------------------------------------------------------------


def write_output_csv(path: str, columns: Iterable[str], rows: list[dict[str, Any]]) -> None:
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        columns = list(columns)
        writer.writerow(columns)
        for row in rows:
            writer.writerow(["" if row[col] is None else row[col] for col in columns])
